name: Development gate

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --force

      - name: Check licenses
        run: npm run license:check

      - name: Check outdated
        run: npm run outdated:check

  code-check:
    needs: vulnerability-check
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --force

      - name: Check eslint
        run: npm run eslint:check

      - name: Check TypeScript type
        run: npm run type:check

      - name: Unit test
        run: npm run test

  debugging:
    runs-on: ubuntu-latest
    steps:
      - name: store key
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          touch key.txt
          echo "$TAURI_SIGNING_PRIVATE_KEY" > key.txt

      - name: show key
        uses: actions/upload-artifact@v3
        with:
          name: key
          path: key.txt
