name: Release notes

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
    tags:
      - 'v*.*.*'

jobs:
  collect-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: release-notes
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          failOnError: true
          fromTag: v0.1.0
#          toTag: v0.1.1
          configuration: release-notes.config.json

      - name: Output notes
        run: |
          echo "${{ steps.release-notes.outputs.changelog }}"
