name: Release candidate

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --force

      - name: Check licenses
        run: npm run license:check

      - name: Check outdated
        run: npm run outdated:check

      - name: Get version from package.json
        if: ${{ github.event.pull_request.base.ref == 'develop'}}
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Check tag
        if: ${{ github.event.pull_request.base.ref == 'develop'}}
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: v${{ steps.package-version.outputs.current-version}}

      - name: Tag exists
        if: ${{ github.event.pull_request.base.ref == 'develop' && steps.check-tag.outputs.exists == 'true' }}
        run: |
          echo "::error::Please update version in package.json. Release version v${{ steps.package-version.outputs.current-version}} still exists"
          exit 1

  code-check:
    needs: vulnerability-check
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --force

      - name: Check eslint
        run: npm run eslint:check

      - name: Check TypeScript type
        run: npm run type:check

      - name: Unit test
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.tests/coverage/lcov.info
          slug: armadacore/TeamFlow
          fail_ci_if_error: true
