name: Tagger

on:
  push:
    branches:
      - develop

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build Changelog
        id: release-notes
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          failOnError: true
          configuration: release-notes.json
          toTag: v${{ steps.package-version.outputs.current-version }}

      - name: Notes output
        run: |
          echo "${{ steps.release-notes.outputs.changelog }}"

#      - name: Update latest release body
#        uses: mini-bomba/create-github-release@v1.1.3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag: v${{ steps.package-version.outputs.current-version }}
#          body: ${{ steps.release-notes.outputs.changelog }}
